### ISSUE TITLE
Question: are the docs updated?

### ISSUE THREAD

**Issue by ianjuma** [scruffy-project/scruffy#6]
Are there massive API changes? the examples on the readme and some docs on the site don't work

**Comment by sksamuel** [comment]
Yes, they are. I'm about to release 1.12 and then I'll update the docs (eta 1/2 days).

**Comment by ianjuma** [comment]
great! thanks.

**Comment by sksamuel** [comment]
1.12.1 is out now, and being used successfully at work. I'll update docs soon now.

**Comment by sksamuel** [comment]
Last post in this thread I promise! 1.12.3 released and docs mostly updated.

**Comment by ianjuma** [comment]
The docs seem to be all over the place and some are missing, 404. What's  the progress, is there an example? Are all the imports included in the example lots of unresolved dependencies.
